ignore:
  - vulnerability: CVE-2025-15467
  - vulnerability: CVE-2025-69420
  - vulnerability: CVE-2026-22796
  - vulnerability: CVE-2025-69419
  - vulnerability: CVE-2025-66199
  - vulnerability: CVE-2025-15468
  - vulnerability: CVE-2025-60876
  - vulnerability: CVE-2025-69421
  - vulnerability: CVE-2025-61726
  - vulnerability: CVE-2025-46394
  - vulnerability: CVE-2026-22795
  - vulnerability: CVE-2025-61728
  - vulnerability: CVE-2025-61731
  - vulnerability: CVE-2025-68160
  - vulnerability: CVE-2025-11187
  - vulnerability: CVE-2024-58251
  - vulnerability: CVE-2025-68119
  - vulnerability: CVE-2025-61730
  - vulnerability: CVE-2025-15469
  - vulnerability: CVE-2025-69418
  - vulnerability: CVE-2025-68121
  - vulnerability: CVE-2025-61732

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
