ignore:
  - vulnerability: CVE-2024-12797
  - vulnerability: CVE-2024-13176
  - vulnerability: CVE-2024-45336
  - vulnerability: CVE-2024-45341
  - vulnerability: CVE-2024-9143
  - vulnerability: CVE-2025-22866
  - vulnerability: CVE-2025-26519
  - vulnerability: GHSA-qxp5-gwg8-xv66
  - vulnerability: CVE-2025-22871
  - vulnerability: GHSA-vvgc-356p-c3xw
  - vulnerability: CVE-2025-22874
  - vulnerability: CVE-2025-47907
  - vulnerability: CVE-2025-4674
  - vulnerability: CVE-2025-9230
  - vulnerability: CVE-2025-47906
  - vulnerability: CVE-2025-4673
  - vulnerability: CVE-2025-9231
  - vulnerability: CVE-2025-9232
  - vulnerability: CVE-2025-61723
  - vulnerability: CVE-2025-61725
  - vulnerability: CVE-2025-58188
  - vulnerability: CVE-2025-58187
  - vulnerability: CVE-2025-58186
  - vulnerability: CVE-2025-61724
  - vulnerability: CVE-2025-47912
  - vulnerability: CVE-2025-58189
  - vulnerability: CVE-2025-58185
  - vulnerability: CVE-2025-58183

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
