version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:

  account-lookup-service:
    image: mojaloop/account-lookup-service:${ACCOUNT_LOOKUP_SERVICE_VERSION}
    env_file:
      - .env
      - perf.env
    scale: 1
    command: sh -c "/opt/app/config-modifier/run.js /opt/app/config/default.json /opt/app/config-modifier/configs/account-lookup-service.js /opt/app/config/default.json && /opt/app/wait4/wait4.js account-lookup-service && npm run migrate && node src/index.js server"
    # ports:
    #   - "4001:4001"
    #   - "4002:4002"
    environment:
      ## Wait 4 Config script
      - WAIT4_CONFIG=./wait4.config.perf-als.js
      - LOG_LEVEL=info
      ## Disable Logging by setting LOG_LEVEL to error
      # - LOG_LEVEL=error
      ## Configuration for EVENT SDK ASYNC OVERRIDES - https://github.com/mojaloop/event-sdk#configuration
      # - EVENT_SDK_ASYNC_OVERRIDE_EVENTS=""
      # - EVENT_SDK_ASYNC_OVERRIDE_EVENTS=log,audit,trace
      ## Disable EVENT SDK LOGs - https://github.com/mojaloop/event-sdk#configuration
      # - EVENT_SDK_LOG_FILTER=""
      ## Allows TraceID to be propogated - https://github.com/mojaloop/event-sdk#configuration
      - EVENT_SDK_TRACEID_PER_VENDOR=false
      ## Disable API Routes from displaying on startup
      - ALS_DISPLAY_ROUTES=false
      ## Configure Switch Endpoint
      - ALS_SWITCH_ENDPOINT=http://callback-handler-svc-cl-sim:3001/admin
      ## Increase UV Threads for IO Operations - https://nodejs.org/api/cli.html#uv_threadpool_sizesize
      - UV_THREADPOOL_SIZE=16
      ## Temporary Cache configuration for v14.2.4-snapshot.3 @ https://github.com/mojaloop/account-lookup-service/pull/461
      # - NODE_CACHE_ENABLED=true
    networks:
      - mojaloop-net
    depends_on:
      mysql-als:
        condition: service_started
    volumes:
      - ./docker/wait4:/opt/app/wait4
      - ./docker/config-modifier:/opt/app/config-modifier
    healthcheck:
      test: wget -q http://localhost:4001/health -O /dev/null || exit 1
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s
    user: root
    profiles:
      - account-lookup-service
      - discovery
      - all-services

  mysql-als:
    image: mysql/mysql-server
    env_file:
      - .env
      - perf.env
    container_name: mysql-als
    ports:
      - "3307:3306"
    volumes:
      - ./docker/sql-als-init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=${DBUSER:-account_lookup}
      - MYSQL_PASSWORD=${DBPASS:-password}
      - MYSQL_DATABASE=${DBUSER:-account_lookup}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - mojaloop-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql-als"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s
    profiles:
      - account-lookup-service
      - discovery
      - all-services
    ## In memory storage - Ref: https://docs.docker.com/storage/tmpfs/
    tmpfs:
      - /var/lib/mysql

  ## Testing Toolkit
  mojaloop-testing-toolkit:
    image: mojaloop/ml-testing-toolkit:v16.1.1
    env_file:
      - .env
      - perf.env
    volumes:
      - "./docker/ml-testing-toolkit/spec_files:/opt/app/spec_files"
      - "./docker/ml-testing-toolkit/test-cases:/opt/app/examples"
    ports:
      - "4040:4040"
      - "5050:5050"
    user: root
    command:
      - sh
      - -c
      - "npm start"
    networks:
      - mojaloop-net
    healthcheck:
      test: ["CMD-SHELL", "nc -z -v localhost 4040"]
      interval: 5s
      timeout: 10s
      start_period: 10s
      retries: 10
    profiles:
      - testing-toolkit
      - all-services

  mojaloop-testing-toolkit-ui:
    image: mojaloop/ml-testing-toolkit-ui:v15.3.0
    env_file:
      - .env
      - perf.env
    ports:
      - "6060:6060"
    environment:
      # - API_BASE_URL=http://localhost:5050
      - AUTH_ENABLED=FALSE
    command:
      - sh
      - /usr/share/nginx/start.sh
    networks:
      - mojaloop-net
    profiles:
      - testing-toolkit
      - all-services

  ttk-provisioning:
    image: mojaloop/ml-testing-toolkit-client-lib:v1.2.0
    env_file:
      - .env
      - perf.env
    volumes:
      - "./docker/ml-testing-toolkit/test-cases/collections:/opt/app/collections"
      - "./docker/ml-testing-toolkit/test-cases/environments:/opt/app/environments"
      - "./reports:/opt/app/reports"
    depends_on:
      mojaloop-testing-toolkit:
        condition: service_healthy
      account-lookup-service:
        condition: service_healthy
    networks:
      - mojaloop-net
    command:
      - sh
      - -c
      - "npm run cli -- -u http://mojaloop-testing-toolkit:5050 -l 2 -i collections/provisioning-perf-als -e environments/default-env.json --save-report --report-format html --report-target file://reports/ttk-provisioning-report.html"
    user: root
    profiles:
      - ttk-provisioning

  ## Generic Callback Handler Service
  # callback-handler-svc:
  #   # scale: 1
  #   scale: 4
  #   image: mojaloop/callback-handler-svc:local
  #   env_file:
  #     - .env
  #     - perf.env
  #   build:
  #     context: ./packages/callback-handler-svc
  #     cache_from:
  #       - mojaloop/callback-handler-svc:local
  #   # ports:
  #   #   - "3001:3001"
  #   networks:
  #     - mojaloop-net
  #   volumes:
  #     - ./packages/callback-handler-svc/config:/opt/app/config
  #     - ./packages/callback-handler-svc/handlers:/opt/app/handlers
  #   environment:
  #     - LOG_LEVEL=info
  #   healthcheck:
  #     test: wget -q http://localhost:3001/health -O /dev/null || exit 1
  #     timeout: 20s
  #     retries: 30
  #     interval: 15s
  #   user: root
  #   profiles:
  #     - simulators
  #     - callback-handler
  #     - all-services

  callback-handler-svc-oracle-sim:
    scale: 1
    image: mojaloop/callback-handler-svc:local
    env_file:
      - .env
      - perf.env
    build:
      context: ./packages/callback-handler-svc
      cache_from:
        - mojaloop/callback-handler-svc:local
    # ports:
    #   - "3001:3001"
    networks:
      - mojaloop-net
    volumes:
      - ./packages/callback-handler-svc/config:/opt/app/config
      - ./packages/callback-handler-svc/handlers:/opt/app/handlers
    environment:
      - LOG_LEVEL=info
    healthcheck:
      test: wget -q http://localhost:3001/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
    user: root
    profiles:
      - simulators
      - callback-handler
      - all-services

  callback-handler-svc-cl-sim:
    scale: 1
    image: mojaloop/callback-handler-svc:local
    env_file:
      - .env
      - ./envs/cl-sim.env
    build:
      context: ./packages/callback-handler-svc
      cache_from:
        - mojaloop/callback-handler-svc:local
    # ports:
    #   - "3001:3001"
    networks:
      - mojaloop-net
    volumes:
      - ./packages/callback-handler-svc/config:/opt/app/config
      - ./packages/callback-handler-svc/handlers:/opt/app/handlers
    environment:
      - LOG_LEVEL=info
    healthcheck:
      test: wget -q http://localhost:3001/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
    user: root
    profiles:
      - simulators
      - callback-handler
      - all-services

  callback-handler-svc-payee-sim:
    scale: 1
    image: mojaloop/callback-handler-svc:local
    env_file:
      - .env
      - ./envs/perffsp2.env
    build:
      context: ./packages/callback-handler-svc
      cache_from:
        - mojaloop/callback-handler-svc:local
    # ports:
    #   - "3001:3001"
    networks:
      - mojaloop-net
    volumes:
      - ./packages/callback-handler-svc/config:/opt/app/config
      - ./packages/callback-handler-svc/handlers:/opt/app/handlers
    environment:
      - LOG_LEVEL=info
    healthcheck:
      test: wget -q http://localhost:3001/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
    user: root
    profiles:
      - simulators
      - callback-handler
      - all-services
      - 2dfsp
      - 4dfsp
      - 8dfsp

  callback-handler-svc-payee-sim-a:
    scale: 1
    image: mojaloop/callback-handler-svc:local
    env_file:
      - .env
      - ./envs/perffsp4.env
    build:
      context: ./packages/callback-handler-svc
      cache_from:
        - mojaloop/callback-handler-svc:local
    # ports:
    #   - "3001:3001"
    networks:
      - mojaloop-net
    volumes:
      - ./packages/callback-handler-svc/config:/opt/app/config
      - ./packages/callback-handler-svc/handlers:/opt/app/handlers
    environment:
      - LOG_LEVEL=info
    healthcheck:
      test: wget -q http://localhost:3001/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
    user: root
    profiles:
      - 4dfsp
      - 8dfsp

  callback-handler-svc-payee-sim-b:
    scale: 1
    image: mojaloop/callback-handler-svc:local
    env_file:
      - .env
      - ./envs/perffsp6.env
    build:
      context: ./packages/callback-handler-svc
      cache_from:
        - mojaloop/callback-handler-svc:local
    # ports:
    #   - "3001:3001"
    networks:
      - mojaloop-net
    volumes:
      - ./packages/callback-handler-svc/config:/opt/app/config
      - ./packages/callback-handler-svc/handlers:/opt/app/handlers
    environment:
      - LOG_LEVEL=info
    healthcheck:
      test: wget -q http://localhost:3001/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
    user: root
    profiles:
      - 8dfsp

  callback-handler-svc-payee-sim-c:
    scale: 1
    image: mojaloop/callback-handler-svc:local
    env_file:
      - .env
      - ./envs/perffsp8.env
    build:
      context: ./packages/callback-handler-svc
      cache_from:
        - mojaloop/callback-handler-svc:local
    # ports:
    #   - "3001:3001"
    networks:
      - mojaloop-net
    volumes:
      - ./packages/callback-handler-svc/config:/opt/app/config
      - ./packages/callback-handler-svc/handlers:/opt/app/handlers
    environment:
      - LOG_LEVEL=info
    healthcheck:
      test: wget -q http://localhost:3001/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
    user: root
    profiles:
      - 8dfsp

  callback-handler-svc-payer-sim:
    scale: 1
    image: mojaloop/callback-handler-svc:local
    env_file:
      - .env
      - ./envs/perffsp1.env
    build:
      context: ./packages/callback-handler-svc
      cache_from:
        - mojaloop/callback-handler-svc:local
    # ports:
    #   - "3001:3001"
    networks:
      - mojaloop-net
    volumes:
      - ./packages/callback-handler-svc/config:/opt/app/config
      - ./packages/callback-handler-svc/handlers:/opt/app/handlers
    environment:
      - LOG_LEVEL=info
    healthcheck:
      test: wget -q http://localhost:3001/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
    user: root
    profiles:
      - simulators
      - callback-handler
      - all-services
      - 2dfsp
      - 4dfsp
      - 8dfsp

  callback-handler-svc-payer-sim-a:
    scale: 1
    image: mojaloop/callback-handler-svc:local
    env_file:
      - .env
      - ./envs/perffsp3.env
    build:
      context: ./packages/callback-handler-svc
      cache_from:
        - mojaloop/callback-handler-svc:local
    # ports:
    #   - "3001:3001"
    networks:
      - mojaloop-net
    volumes:
      - ./packages/callback-handler-svc/config:/opt/app/config
      - ./packages/callback-handler-svc/handlers:/opt/app/handlers
    environment:
      - LOG_LEVEL=info
    healthcheck:
      test: wget -q http://localhost:3001/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
    user: root
    profiles:
      - 4dfsp
      - 8dfsp

  callback-handler-svc-payer-sim-b:
    scale: 1
    image: mojaloop/callback-handler-svc:local
    env_file:
      - .env
      - ./envs/perffsp5.env
    build:
      context: ./packages/callback-handler-svc
      cache_from:
        - mojaloop/callback-handler-svc:local
    # ports:
    #   - "3001:3001"
    networks:
      - mojaloop-net
    volumes:
      - ./packages/callback-handler-svc/config:/opt/app/config
      - ./packages/callback-handler-svc/handlers:/opt/app/handlers
    environment:
      - LOG_LEVEL=info
    healthcheck:
      test: wget -q http://localhost:3001/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
    user: root
    profiles:
      - 8dfsp

  callback-handler-svc-payer-sim-c:
    scale: 1
    image: mojaloop/callback-handler-svc:local
    env_file:
      - .env
      - ./envs/perffsp7.env
    build:
      context: ./packages/callback-handler-svc
      cache_from:
        - mojaloop/callback-handler-svc:local
    # ports:
    #   - "3001:3001"
    networks:
      - mojaloop-net
    volumes:
      - ./packages/callback-handler-svc/config:/opt/app/config
      - ./packages/callback-handler-svc/handlers:/opt/app/handlers
    environment:
      - LOG_LEVEL=info
    healthcheck:
      test: wget -q http://localhost:3001/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
    user: root
    profiles:
      - 8dfsp
