{
 "title": "Mojaloop - Central-Ledger - Performance Characterization",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Models - Cache Hits (True vs False)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate( moja_cl_model_participant_count{queryName=~\"model_.*Cached\"}[$__rate_interval])) by (queryName, hit) ",
     "legendFormat": "{{queryName}}-{{hit}}"
    }
   ]
  },
  {
   "title": "Models - Processed per sec",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_cl_model_transfer_count[$__rate_interval])) by (queryName)",
     "legendFormat": "{{queryName}}"
    },
    {
     "expr": "sum(rate(moja_cl_model_participant_count[$__rate_interval])) by (queryName)",
     "legendFormat": "{{queryName}}"
    },
    {
     "expr": "sum(rate(moja_cl_model_position_count[$__rate_interval])) by (queryName)",
     "legendFormat": "{{queryName}}"
    }
   ]
  },
  {
   "title": "Models - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_cl_model_transfer_sum[$__rate_interval]) / rate(moja_cl_model_transfer_count[$__rate_interval]) >=0 ) by (queryName, kubernetes_pod_name)",
     "legendFormat": "{{queryName}} - {{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(rate(moja_cl_model_participant_sum[$__rate_interval]) / rate(moja_cl_model_participant_count[$__rate_interval]) >=0 ) by (queryName, kubernetes_pod_name)",
     "legendFormat": "{{queryName}} - {{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(rate(moja_cl_model_position_sum[$__rate_interval]) / rate(moja_cl_model_position_count[$__rate_interval]) >=0 ) by (queryName, kubernetes_pod_name)",
     "legendFormat": "{{queryName}} - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Operations - Processed per second",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_cl_handler_transfers_count[$__rate_interval])) by (funcName)",
     "legendFormat": "{{funcName}}"
    },
    {
     "expr": "sum(rate(moja_cl_handlers_transfer_validator_count[$__rate_interval])) by (funcName)",
     "legendFormat": "{{funcName}}"
    },
    {
     "expr": "sum(rate(moja_cl_domain_transfer_count[$__rate_interval])) by (funcName)",
     "legendFormat": "{{funcName}}"
    },
    {
     "expr": "sum(rate(moja_cl_domain_position_count[$__rate_interval])) by (funcName)",
     "legendFormat": "{{funcName}}"
    }
   ]
  },
  {
   "title": "Operations - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_cl_handler_transfers_sum[$__rate_interval]) / rate(moja_cl_handler_transfers_count[$__rate_interval]) >=0) by (funcName, kubernetes_pod_name)",
     "legendFormat": "{{funcName}} - {{kubernetes_pod_name}} - {{mode}}"
    },
    {
     "expr": "avg(rate(moja_cl_handlers_transfer_validator_sum[$__rate_interval]) / rate(moja_cl_handlers_transfer_validator_count[$__rate_interval]) >=0) by (funcName, kubernetes_pod_name)",
     "legendFormat": "{{funcName}} - {{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(rate(moja_cl_domain_transfer_sum[$__rate_interval]) / rate(moja_cl_domain_transfer_count[$__rate_interval]) >=0) by (funcName, kubernetes_pod_name)",
     "legendFormat": "{{funcName}} - {{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(rate(moja_cl_domain_position_sum[$__rate_interval]) / rate(moja_cl_domain_position_count[$__rate_interval]) >=0) by (funcName, kubernetes_pod_name)",
     "legendFormat": "{{funcName}} - {{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(rate(moja_cl_transfer_position_sum[$__rate_interval]) / rate(moja_cl_transfer_position_count[$__rate_interval]) >=0) by (funcName, kubernetes_pod_name)",
     "legendFormat": "Position handler - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Central Ledger Lag by Consumer Group",
   "type": "timeseries",
   "description": "Central Ledger Lag by Consumer Group",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"topic-.*\", consumergroup=~\"cl-group-.*\"}) by (consumergroup, topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Central-Service - Processed per sec",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(moja_cl_transfer_prepare_count{serviceName=~\"central-handler-prepare|central-service\"}[$__rate_interval])) by (app_kubernetes_io_name)",
     "legendFormat": "{{app_kubernetes_io_name}}"
    },
    {
     "expr": "sum(rate(moja_cl_transfer_position_count{serviceName=~\"central-handler-position|central-service\", }[$__rate_interval])) by (app_kubernetes_io_name)",
     "legendFormat": "{{app_kubernetes_io_name}}-position"
    },
    {
     "expr": "sum(rate(moja_cl_transfer_fulfil_count{serviceName=~\"central-handler-fulfil|central-service\"}[$__rate_interval])) by (app_kubernetes_io_name)",
     "legendFormat": "{{app_kubernetes_io_name}}"
    },
    {
     "expr": "sum(rate(moja_cl_transfer_prepare_count{serviceName=~\"central-handler-prepare|central-service\"}[$__rate_interval])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(moja_cl_transfer_fulfil_count{serviceName=~\"central-handler-fulfil|central-service\"}[$__rate_interval])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(moja_cl_transfer_position_count{serviceName=~\"central-handler-position|central-service\"}[$__rate_interval])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Transfers Prepares / sec",
   "type": "stat",
   "description": "Transfers Prepares / sec",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(moja_cl_transfer_prepare_count{serviceName=~\"central-handler-prepare|central-service\"}[$__rate_interval]))",
     "legendFormat": "Transfers Prepare / sec"
    }
   ]
  },
  {
   "title": "Transfer Positions / sec",
   "type": "stat",
   "description": "Transfer Positions / sec",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(moja_cl_transfer_position_count{serviceName=~\"central-handler-prepare|central-service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Transfers Fullfills / sec",
   "type": "stat",
   "description": "Transfers Fullfills / sec",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(moja_cl_transfer_fulfil_count{serviceName=~\"central-handler-fulfil|central-service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Central-Service - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(moja_cl_transfer_prepare_sum{serviceName=~\"central-handler-prepare|central-service\"}[$__rate_interval]) / rate(moja_cl_transfer_prepare_count{serviceName=~\"central-handler-prepare|central-service\"}[$__rate_interval]) >=0",
     "legendFormat": "Transfer Prepare - {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(moja_cl_transfer_position_sum{serviceName=~\"central-handler-position|central-service\"}[$__rate_interval]) / rate(moja_cl_transfer_position_count{serviceName=~\"central-handler-position|central-service\"}[$__rate_interval]) >=0",
     "legendFormat": "Transfer Position - {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(moja_cl_transfer_fulfil_sum{serviceName=~\"central-handler-fulfil|central-service\"}[$__rate_interval]) / rate(moja_cl_transfer_fulfil_count{serviceName=~\"central-handler-fulfil|central-service\"}[$__rate_interval]) >=0 ",
     "legendFormat": "Transfer Fulfil - {{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(rate(moja_cl_transfer_prepare_sum{serviceName=~\"central-handler-prepare|central-service\"}[$__rate_interval]) / rate(moja_cl_transfer_prepare_count{serviceName=~\"central-handler-prepare|central-service\"}[$__rate_interval]) >=0) ",
     "legendFormat": "Transfer Prepare - Average"
    },
    {
     "expr": "avg(rate(moja_cl_transfer_position_sum{serviceName=~\"central-handler-position|central-service\"}[$__rate_interval]) / rate(moja_cl_transfer_position_count{serviceName=~\"central-handler-position|central-service\"}[$__rate_interval]) >=0) ",
     "legendFormat": "Transfer Position - Average"
    },
    {
     "expr": "avg(rate(moja_cl_transfer_fulfil_sum{serviceName=~\"central-handler-fulfil|central-service\"}[$__rate_interval]) / rate(moja_cl_transfer_fulfil_count{serviceName=~\"central-handler-fulfil|central-service\"}[$__rate_interval]) >=0) ",
     "legendFormat": "Transfer Fulfil - Average"
    }
   ]
  },
  {
   "title": "Number of Transfers Saved in DB",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time( moja_cl_model_transfer_count{queryName=\"facade_saveTransferPrepared_transaction\", success=\"true\"}[$__interval]))",
     "legendFormat": "Transfer Prepares (success)"
    }
   ]
  },
  {
   "title": "CPU Usage by App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Central Services Total CPU Usage",
   "type": "gauge",
   "description": "Central Services Total CPU Usage",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*centralledger.*'}[2m]))"
    }
   ]
  },
  {
   "title": "Transfer Prepare Handler CPU Usage",
   "type": "gauge",
   "description": "Transfer Prepare Handler CPU Usage",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*centralledger-handler-transfer-prepare.*'}[2m]))"
    }
   ]
  },
  {
   "title": "Transfer Position Handler CPU Usage",
   "type": "gauge",
   "description": "Transfer Position Handler CPU Usage",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*centralledger-handler-transfer-position.*'}[2m]))"
    }
   ]
  },
  {
   "title": "Transfer Fulfil Handler CPU Usage",
   "type": "gauge",
   "description": "Transfer Fulfil Handler CPU Usage",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*centralledger-handler-transfer-fulfil.*'}[2m]))"
    }
   ]
  },
  {
   "title": "CPU Usage by Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Central-Service  - CPU Usage in Seconds by Pod",
   "type": "timeseries",
   "description": "Central-Service  - CPU Usage in Seconds by Pod",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(moja_cl_process_cpu_seconds_total{serviceName=~\"central.*\"}[2m]) * 100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Central-Service  - Event Loop Lag in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(moja_cl_nodejs_eventloop_lag_seconds{serviceName=~\"central.*\"}) by (serviceName)",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "Central-Service - # Pods for each Components",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*-centralledger-.*\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}