{
 "title": "Mojaloop - ML-API",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processing time stats",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(moja_ml_tx_transfer_bucket{le=\"+Inf\"}[${__range_s}s]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(increase(moja_ml_tx_transfer_bucket{le=\"1\"}[${__range_s}s]))",
     "legendFormat": "Less than 1 sec"
    },
    {
     "expr": "sum(increase(moja_ml_tx_transfer_bucket{le=\"+Inf\"}[${__range_s}s])) - sum(increase(moja_ml_tx_transfer_prepare_bucket{le=\"1\"}[${__range_s}s]))",
     "legendFormat": "More than 1 sec"
    },
    {
     "expr": "sum(increase(moja_ml_tx_transfer_bucket{le=\"+Inf\"}[${__range_s}s])) - sum(increase(moja_ml_tx_transfer_prepare_bucket{le=\"2\"}[${__range_s}s]))",
     "legendFormat": "More than 2 sec"
    },
    {
     "expr": "sum(increase(moja_ml_tx_transfer_bucket{le=\"+Inf\"}[${__range_s}s])) - sum(increase(moja_ml_tx_transfer_prepare_bucket{le=\"5\"}[${__range_s}s]))",
     "legendFormat": "More than 5 sec"
    }
   ]
  },
  {
   "title": "Mojaloop",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mojaloop - Processed per sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_ml_tx_transfer_count[$__rate_interval]))",
     "legendFormat": "moja_ml_tx_transfer - avg"
    },
    {
     "expr": "sum(rate(moja_ml_tx_transfer_prepare_count[$__rate_interval]))",
     "legendFormat": "moja_ml_tx_transfer_prepare - avg"
    },
    {
     "expr": "sum(rate(moja_ml_tx_transfer_fulfil_count[$__rate_interval]))",
     "legendFormat": "moja_ml_tx_transfer_fulfil - avg"
    },
    {
     "expr": "sum(rate(moja_ml_transfer_prepare_count{serviceName=\"ml-service\"}[$__rate_interval])) by (app, success)",
     "legendFormat": "Transfers API Prepare - success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ml_transfer_fulfil_count{serviceName=\"ml-service\"}[$__rate_interval])) by (app, success)",
     "legendFormat": "Transfers API Fulfill - success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ml_notification_event_delivery_count{serviceName=\"ml-handler-notification\"}[$__rate_interval])) by (app, action, status, success)",
     "legendFormat": "Notification Delivery - {{action}} - {{status}} - success:{{success}}"
    }
   ]
  },
  {
   "title": "Mojaloop - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_ml_transfer_prepare_sum{serviceName=\"ml-service\"}[$__rate_interval]) / rate(moja_ml_transfer_prepare_count{serviceName=\"ml-service\"}[$__rate_interval]) >=0)",
     "legendFormat": "Transfer API Prepare - Average"
    },
    {
     "expr": "avg(rate(moja_ml_transfer_fulfil_sum{serviceName=\"ml-service\"}[$__rate_interval]) / rate(moja_ml_transfer_fulfil_count{serviceName=\"ml-service\"}[$__rate_interval]) >=0)",
     "legendFormat": "Transfer API Fulfil - Average"
    },
    {
     "expr": "avg(rate(moja_ml_notification_event_delivery_sum{serviceName=\"ml-handler-notification\"}[$__rate_interval]) / rate(moja_ml_notification_event_delivery_count{serviceName=\"ml-handler-notification\"}[$__rate_interval]) >=0) by (action, status, success)",
     "legendFormat": "Notification Deliveries - {{action}} - {{status}} - success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ml_tx_transfer_sum[$__rate_interval]) / irate(moja_ml_tx_transfer_count[$__rate_interval]) >=0)",
     "legendFormat": "moja_ml_tx_transfer - avg"
    },
    {
     "expr": "avg(rate(moja_ml_tx_transfer_prepare_sum[$__rate_interval]) / rate(moja_ml_tx_transfer_prepare_count[$__rate_interval]) >=0)",
     "legendFormat": "moja_ml_tx_transfer_prepare - avg"
    },
    {
     "expr": "avg(rate(moja_ml_tx_transfer_fulfil_sum[$__rate_interval]) / rate(moja_ml_tx_transfer_fulfil_count[$__rate_interval]) >=0)",
     "legendFormat": "moja_ml_tx_transfer_fulfil - avg"
    }
   ]
  },
  {
   "title": "Current OP/s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Financial Transfers / Sec",
   "type": "stat",
   "description": "Financial Transfers / Sec",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(moja_ml_tx_transfer_count[$__rate_interval]))",
     "legendFormat": "Financial Transfers / sec"
    }
   ]
  },
  {
   "title": "Financial Prepares / sec",
   "type": "stat",
   "description": "Financial Prepares / sec",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(moja_ml_tx_transfer_prepare_count[$__rate_interval]))",
     "legendFormat": "Transfers / Sec"
    }
   ]
  },
  {
   "title": "Financial Fulils / sec",
   "type": "stat",
   "description": "Financial Fulils / sec",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(moja_ml_tx_transfer_fulfil_count[$__rate_interval]))",
     "legendFormat": "Financial Fulfils / sec"
    }
   ]
  },
  {
   "title": "Transfers API Prepares / sec",
   "type": "stat",
   "description": "Transfers API Prepares / sec",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(moja_ml_transfer_prepare_count{serviceName=\"ml-service\"}[$__rate_interval]))",
     "legendFormat": "Transfers Prepare / sec"
    }
   ]
  },
  {
   "title": "Transfers API Fullfills / sec",
   "type": "stat",
   "description": "Transfers API Fullfills / sec",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(moja_ml_transfer_fulfil_count{serviceName=\"ml-service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Notification Events / Sec",
   "type": "stat",
   "description": "Notification Events / Sec",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(moja_ml_notification_event_count{serviceName=~\"ml-handler-notification|ml-service\"}[$__rate_interval]))",
     "legendFormat": "Notification Events / sec"
    }
   ]
  },
  {
   "title": "Financial Transfers 95th Quantile",
   "type": "stat",
   "description": "Financial Transfers 95th Quantile",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(moja_ml_tx_transfer_bucket[${__range_s}s])) by (le))"
    }
   ]
  },
  {
   "title": "% > 1 Sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(moja_ml_tx_transfer_bucket{le=\"+Inf\"}[${__range_s}s])) - sum(increase(moja_ml_tx_transfer_bucket{le=\"1\"}[${__range_s}s]))) / sum(increase(moja_ml_tx_transfer_bucket{le=\"+Inf\"}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ML API Lag by  Consumer Group",
   "type": "timeseries",
   "description": "ML API Lag by  Consumer Group",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"topic-.*\", consumergroup=~\"ml-group.*\"}) by (consumergroup, topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ML-API - Processed per sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_ml_tx_transfer_count[$__rate_interval])) by (success)",
     "legendFormat": "moja_ml_tx_transfer - success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ml_tx_transfer_prepare_count[$__rate_interval])) by (success)",
     "legendFormat": "moja_ml_tx_transfer_prepare - success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ml_tx_transfer_fulfil_count[$__rate_interval])) by (success)",
     "legendFormat": "moja_ml_tx_transfer_fulfil - success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ml_transfer_prepare_count{serviceName=\"ml-service\"}[$__rate_interval])) by (app, success)",
     "legendFormat": "Transfers API Prepare - success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ml_transfer_fulfil_count{serviceName=\"ml-service\"}[$__rate_interval])) by (app, success)",
     "legendFormat": "Transfers API Fulfill - success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ml_notification_event_count{serviceName=~\"ml-handler-notification|ml-service\"}[$__rate_interval])) by (app, success)",
     "legendFormat": "Notification Events - success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ml_notification_event_process_msg_count{serviceName=~\"ml-handler-notification|ml-service\"}[$__rate_interval])) by (app, action, success)",
     "legendFormat": "Notification Events - {{action}} - success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ml_notification_event_delivery_count{serviceName=\"~ml-handler-notification|ml-service\"}[$__rate_interval])) by (app, action, status, success)",
     "legendFormat": "Notification Delivery - {{action}} - {{status}} - success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ml_notification_event_count{serviceName=~\"ml-handler-notification|ml-service\"}[$__rate_interval])) by (instance, kubernetes_pod_name, success)",
     "legendFormat": "{{instance}} {{kubernetes_pod_name}} - success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ml_notification_event_getEndpoint_count{serviceName=~\"ml-handler-notification|ml-service\"}[$__rate_interval])) by (success)",
     "legendFormat": "Notification GetEndpoint - success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ml_tx_transfer_count[$__rate_interval]))",
     "legendFormat": "moja_ml_tx_transfer - avg"
    },
    {
     "expr": "sum(rate(moja_ml_tx_transfer_prepare_count[$__rate_interval]))",
     "legendFormat": "moja_ml_tx_transfer_prepare - avg"
    },
    {
     "expr": "sum(rate(moja_ml_tx_transfer_fulfil_count[$__rate_interval]))",
     "legendFormat": "moja_ml_tx_transfer_fulfil - avg"
    }
   ]
  },
  {
   "title": "ML-API - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_ml_transfer_prepare_sum{serviceName=\"ml-service\"}[$__rate_interval]) / rate(moja_ml_transfer_prepare_count{serviceName=\"ml-service\"}[$__rate_interval]) >=0)",
     "legendFormat": "Transfer API Prepare - Average"
    },
    {
     "expr": "avg(rate(moja_ml_transfer_fulfil_sum{serviceName=\"ml-service\"}[$__rate_interval]) / rate(moja_ml_transfer_fulfil_count{serviceName=\"ml-service\"}[$__rate_interval]) >=0)",
     "legendFormat": "Transfer API Fulfil - Average"
    },
    {
     "expr": "avg(rate(moja_ml_notification_event_sum{serviceName=\"ml-handler-notification\"}[$__rate_interval]) / rate(moja_ml_notification_event_count{serviceName=\"ml-handler-notification\"}[$__rate_interval]) >=0)",
     "legendFormat": "Notification Events - Average"
    },
    {
     "expr": "avg(rate(moja_ml_notification_event_delivery_sum{serviceName=\"ml-handler-notification\"}[$__rate_interval]) / rate(moja_ml_notification_event_delivery_count{serviceName=\"ml-handler-notification\"}[$__rate_interval]) >=0) by (action, status, success)",
     "legendFormat": "Notification Deliveries - {{action}} - {{status}} - success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ml_tx_transfer_sum[$__rate_interval]) / rate(moja_ml_tx_transfer_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "moja_ml_tx_transfer - success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ml_tx_transfer_prepare_sum[$__rate_interval]) / rate(moja_ml_tx_transfer_prepare_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "moja_ml_tx_transfer_prepare - success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ml_tx_transfer_fulfil_sum[$__rate_interval]) / rate(moja_ml_tx_transfer_fulfil_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "moja_ml_tx_transfer_fulfil - success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ml_tx_transfer_sum[$__rate_interval]) / irate(moja_ml_tx_transfer_count[$__rate_interval]) >=0)",
     "legendFormat": "moja_ml_tx_transfer - avg"
    },
    {
     "expr": "avg(rate(moja_ml_tx_transfer_prepare_sum[$__rate_interval]) / rate(moja_ml_tx_transfer_prepare_count[$__rate_interval]) >=0)",
     "legendFormat": "moja_ml_tx_transfer_prepare - avg"
    },
    {
     "expr": "avg(rate(moja_ml_tx_transfer_fulfil_sum[$__rate_interval]) / rate(moja_ml_tx_transfer_fulfil_count[$__rate_interval]) >=0)",
     "legendFormat": "moja_ml_tx_transfer_fulfil - avg"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ML-API- Notification Handler Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(moja_ml_notification_event_count{serviceName=~\"ml-handler-notification|ml-service\", success!='true'}[$__rate_interval])) by (app, success, error)",
     "legendFormat": "{{error}}"
    },
    {
     "expr": "sum(rate(moja_ml_notification_event_count{serviceName=~\"ml-handler-notification|ml-service\", success!='true'}[$__rate_interval])) by (app, success, error, kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}} - {{error}}"
    },
    {
     "expr": "rate(moja_ml_notification_event_sum{serviceName=~\"ml-handler-notification|ml-service\", success!='true'}[$__rate_interval]) / rate(moja_ml_notification_event_count{serviceName=~\"ml-handler-notification|ml-service\", success!='true'}[$__rate_interval])"
    },
    {
     "expr": "rate(moja_ml_notification_event_sum{serviceName=~\"ml-handler-notification|ml-service\", success!='false'}[$__rate_interval]) / rate(moja_ml_notification_event_count{serviceName=~\"ml-handler-notification|ml-service\", success!='false'}[$__rate_interval])"
    },
    {
     "expr": "sum(rate(moja_ml_tx_transfer_bucket[$__rate_interval])) by (le)"
    }
   ]
  },
  {
   "title": "Total Notification Handler Errors for range ",
   "type": "timeseries",
   "description": "Total Notification Handler Errors for range ",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(moja_ml_notification_event_bucket{le=\"+Inf\", serviceName=~\"ml-handler-notification|ml-service\", success!='true'}[${__range_s}s])) by (app, success, error)",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "CPU Usage by App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mojaloop API Adapter Total CPU Usage",
   "type": "gauge",
   "description": "Mojaloop API Adapter Total CPU Usage",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate (container_cpu_usage_seconds_total{pod_name=~'.*ml-api.*'}[2m]))"
    }
   ]
  },
  {
   "title": "ML API Service CPU Usage",
   "type": "gauge",
   "description": "ML API Service CPU Usage",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*ml-api-adapter-service.*'}[2m]))"
    }
   ]
  },
  {
   "title": "ML API Notification CPU Usage",
   "type": "gauge",
   "description": "ML API Notification CPU Usage",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*ml-api-adapter-handler-notification.*'}[2m]))"
    }
   ]
  },
  {
   "title": "Resource Usage by Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ML API - Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "moja_ml_nodejs_heap_size_total_bytes{serviceName=~\"ml-s.*\"}",
     "legendFormat": "heap_total-{{kubernetes_pod_name}}"
    },
    {
     "expr": "moja_ml_nodejs_heap_size_used_bytes{serviceName=~\"ml-s.*\"}",
     "legendFormat": "heap_used-{{kubernetes_pod_name}}"
    },
    {
     "expr": "moja_ml_nodejs_external_memory_bytes{serviceName=~\"ml-s.*\"}",
     "legendFormat": "ext_memory-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "ML-API  -  CPU Usage in Seconds by Pod",
   "type": "timeseries",
   "description": "ML-API  -  CPU Usage in Seconds by Pod",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(moja_ml_process_cpu_seconds_total{serviceName=~\"ml-.*\"}[$__rate_interval]) * 100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ML-API - # Nodes for each Components",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*ml-api-.*\"}",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*simnotifhandler.*\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "ML-API  - Event Loop Lag in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(moja_ml_nodejs_eventloop_lag_seconds{serviceName=~\"ml.*\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}