{
 "title": "Central Ledger DB",
 "time": { "from": "2023-07-29T03:33:07.521Z", "to": "2023-08-14T03:33:07.521Z" },
 "panels": [
  {
   "title": "COMMITED State Changes In DB between time range",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "central_ledger",
     "rawSql": "SELECT COUNT(t1.transferId) \nFROM central_ledger.transferStateChange t1 \nWHERE transferStateId = 'COMMITTED' \nAND createdDate between $__timeFrom() \nAND $__timeTo() AND t1.createdDate = (\n  SELECT MAX(t2.createdDate)\n  FROM central_ledger.transferStateChange t2\n  WHERE t2.transferId = t1.transferId\n)\n                               "
    }
   ]
  },
  {
   "title": "Transfer state changes excluding COMMITTED between time range",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(transferId) FROM central_ledger.transferStateChange WHERE transferStateId != 'COMMITTED' AND createdDate between $__timeFrom() AND $__timeTo()"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "rawSql": "ANALYZE TABLE transfer;" },
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT table_schema \"DB Name\",\n        ROUND(SUM(data_length + index_length) / 1024 / 1024, 1) \"DB Size in MB\" \nFROM information_schema.tables \nGROUP BY table_schema; "
    }
   ]
  },
  {
   "title": "Last Transfer State Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(central_ledger.transfer.transferId), central_ledger.transferStateChange.transferStateId\nFROM central_ledger.transfer \nLEFT JOIN central_ledger.transferStateChange ON central_ledger.transfer.transferId=central_ledger.transferStateChange.transferId  \nWHERE central_ledger.transferStateChange.transferStateChangeId IN (\n  SELECT MAX(central_ledger.transferStateChange.transferStateChangeId)\n  FROM central_ledger.transfer \n  LEFT JOIN central_ledger.transferStateChange ON central_ledger.transfer.transferId=central_ledger.transferStateChange.transferId \n  WHERE central_ledger.transferStateChange.createdDate between $__timeFrom() AND $__timeTo() \n  GROUP BY central_ledger.transfer.transferId\n) \nGROUP BY central_ledger.transferStateChange.transferStateId"
    }
   ]
  }
 ]
}