{
 "title": "Mojaloop - Quoting Service",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Database Cache Hits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Models - Cache Hits (True vs False)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(moja_qs_database_get_cache_value[$__rate_interval])) by (queryName, hit) ",
     "legendFormat": "{{queryName}}-{{hit}}"
    }
   ]
  },
  { "title": "Quote Resource Metric Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Ing GET /quotes/* requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 1, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(moja_qs_quotes_id_get_count)"
    }
   ]
  },
  {
   "title": "Ing PUT /quotes/* requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(moja_qs_quotes_id_put_count)"
    }
   ]
  },
  {
   "title": "Ing PUT /quotes/*/error requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(moja_qs_quotes_id_put_error_count)"
    }
   ]
  },
  {
   "title": "Ing POST /quotes requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "sum(moja_qs_quotes_post_count)" }
   ]
  },
  {
   "title": "Quote Resource Performance Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "Quote Handlers Ingress - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_qs_quotes_post_sum[$__rate_interval]) / rate(moja_qs_quotes_post_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "postQuotes success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_qs_quotes_id_put_sum[$__rate_interval]) / rate(moja_qs_quotes_id_put_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putQuotesByID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_qs_quotes_id_get_sum[$__rate_interval]) / rate(moja_qs_quotes_id_get_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "getQuotesByID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_qs_quotes_id_put_error_sum[$__rate_interval]) / rate(moja_qs_quotes_id_put_error_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putQuotesByIDError success:{{success}}"
    }
   ]
  },
  {
   "title": "Quote Handler Ingress - Processing Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_qs_quotes_id_put_error_count[$__rate_interval])) by (success)",
     "legendFormat": "putQuotesIDError success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_qs_quotes_id_get_count[$__rate_interval])) by (success)",
     "legendFormat": "getQuotesByID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_qs_quotes_id_put_count[$__rate_interval])) by (success)",
     "legendFormat": "putQuotesByID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_qs_quotes_post_count[$__rate_interval])) by (success)",
     "legendFormat": "postQuotes success:{{success}}"
    }
   ]
  },
  {
   "title": "Quote Model - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_qs_model_quote_sum[$__rate_interval]) / rate(moja_qs_model_quote_count[$__rate_interval]) >=0) by (success, queryName)",
     "legendFormat": "{{queryName}} success:{{success}}"
    }
   ]
  },
  {
   "title": "Quote Model - Processing Per Second",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_qs_model_quote_count[$__rate_interval])) by (success, queryName)",
     "legendFormat": "{{queryName}} success:{{success}}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "QS Total CPU Usage",
   "type": "gauge",
   "description": "QS Total CPU Usage",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate (container_cpu_usage_seconds_total{pod_name=~'.*quoting-service.*'}[2m]))"
    }
   ]
  },
  { "title": "Resource Usage by Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "QS - Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "moja_qs_nodejs_heap_size_total_bytes{serviceName=~\"quoting-service.*\"}",
     "legendFormat": "heap_total-{{instance}} {{kubernetes_pod_name}}"
    },
    {
     "expr": "moja_qs_nodejs_heap_size_used_bytes{serviceName=~\"quoting-service.*\"}",
     "legendFormat": "heap_used-{{instance}} {{kubernetes_pod_name}}"
    },
    {
     "expr": "moja_qs_nodejs_external_memory_bytes{serviceName=~\"quoting-service.*\"}",
     "legendFormat": "ext_memory-{{instance}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "QS  -  CPU Usage in Seconds by Pod",
   "type": "timeseries",
   "description": "QS  -  CPU Usage in Seconds by Pod",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(moja_qs_process_cpu_seconds_total{serviceName=~\"account-lookup.*\"}[30s]) * 100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "QS - # Nodes for each Components",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*quoting-service.*\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "QS  - Event Loop Lag in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(moja_qs_nodejs_eventloop_lag_seconds{serviceName=~\"quoting-service.*\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}