{
 "title": "Mojaloop - Central-Ledger - Performance Characterization",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Models - Cache Hits (True vs False)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate( moja_cl_model_participant_count{queryName=~\"model_.*Cached\"}[30s])) by (queryName, hit) ",
     "legendFormat": "{{queryName}}-{{hit}}"
    }
   ]
  },
  {
   "title": "Models - Processed per sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(moja_cl_model_transfer_count[120s])) by (queryName)",
     "legendFormat": "{{queryName}}"
    },
    {
     "expr": "sum(rate(moja_cl_model_participant_count[120s])) by (queryName)",
     "legendFormat": "{{queryName}}"
    },
    {
     "expr": "sum(rate(moja_cl_model_position_count[120s])) by (queryName)",
     "legendFormat": "{{queryName}}"
    }
   ]
  },
  {
   "title": "Models - Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(moja_cl_model_transfer_sum[30s]) / irate(moja_cl_model_transfer_count[30s])",
     "legendFormat": "{{queryName}} - {{kubernetes_pod_name}}"
    },
    {
     "expr": "irate(moja_cl_model_participant_sum[30s]) / irate(moja_cl_model_participant_count[30s])",
     "legendFormat": "{{queryName}} - {{kubernetes_pod_name}}"
    },
    {
     "expr": "irate(moja_cl_model_position_sum[30s]) / irate(moja_cl_model_position_count[30s])",
     "legendFormat": "{{queryName}} - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Operations - Processed per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(moja_cl_handler_transfers_count[30s])) by (funcName)",
     "legendFormat": "{{funcName}}"
    },
    {
     "expr": "sum(rate(moja_cl_handlers_transfer_validator_count[30s])) by (funcName)",
     "legendFormat": "{{funcName}}"
    },
    {
     "expr": "sum(rate(moja_cl_domain_transfer_count[30s])) by (funcName)",
     "legendFormat": "{{funcName}}"
    },
    {
     "expr": "sum(rate(moja_cl_domain_position_count[30s])) by (funcName)",
     "legendFormat": "{{funcName}}"
    }
   ]
  },
  {
   "title": "Operations - Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(moja_cl_handler_transfers_sum[30s]) / irate(moja_cl_handler_transfers_count[30s])",
     "legendFormat": "{{funcName}} - {{kubernetes_pod_name}} - {{mode}}"
    },
    {
     "expr": "irate(moja_cl_handlers_transfer_validator_sum[30s]) / irate(moja_cl_handlers_transfer_validator_count[30s])",
     "legendFormat": "{{funcName}} - {{kubernetes_pod_name}}"
    },
    {
     "expr": "irate(moja_cl_domain_transfer_sum[30s]) / irate(moja_cl_domain_transfer_count[30s])",
     "legendFormat": "{{funcName}} - {{kubernetes_pod_name}}"
    },
    {
     "expr": "irate(moja_cl_domain_position_sum[30s]) / irate(moja_cl_domain_position_count[30s])",
     "legendFormat": "{{funcName}} - {{kubernetes_pod_name}}"
    },
    {
     "expr": "irate(moja_cl_transfer_position_sum[30s]) / irate(moja_cl_transfer_position_count[30s])",
     "legendFormat": "Position handler - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Central Ledger Lag by Consumer Group",
     "type": "graph",
     "description": "Central Ledger Lag by Consumer Group",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_lag{topic=~\"topic-.*\", consumergroup=~\"cl-group-.*\"}) by (consumergroup, topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Central-Service - Processed per sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(moja_cl_transfer_prepare_count{serviceName=\"central-handler-prepare\"}[30s])) by (app_kubernetes_io_name)",
     "legendFormat": "{{app_kubernetes_io_name}}"
    },
    {
     "expr": "sum(rate(moja_cl_transfer_position_count{serviceName=\"central-handler-position\", }[30s])) by (app_kubernetes_io_name)",
     "legendFormat": "{{app_kubernetes_io_name}}-position"
    },
    {
     "expr": "sum(rate(moja_cl_transfer_fulfil_count{serviceName=\"central-handler-fulfil\"}[30s])) by (app_kubernetes_io_name)",
     "legendFormat": "{{app_kubernetes_io_name}}"
    },
    {
     "expr": "sum(rate(moja_cl_transfer_prepare_count{serviceName=\"central-handler-prepare\"}[30s])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(moja_cl_transfer_fulfil_count{serviceName=\"central-handler-fulfil\"}[30s])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(moja_cl_transfer_position_count{serviceName=\"central-handler-position\"}[30s])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Transfers Prepares / sec",
   "type": "stat",
   "description": "Transfers Prepares / sec",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(moja_cl_transfer_prepare_count{serviceName=\"central-handler-prepare\"}[120s]))",
     "legendFormat": "Transfers Prepare / sec"
    }
   ]
  },
  {
   "title": "Transfer Positions / sec",
   "type": "stat",
   "description": "Transfer Positions / sec",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(moja_cl_transfer_position_count{serviceName=\"central-handler-prepare\"}[120s]))"
    }
   ]
  },
  {
   "title": "Transfers Fullfills / sec",
   "type": "stat",
   "description": "Transfers Fullfills / sec",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(moja_cl_transfer_fulfil_count{serviceName=\"central-handler-fulfil\"}[120s]))"
    }
   ]
  },
  {
   "title": "Central-Service - Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(moja_cl_transfer_prepare_sum{serviceName=\"central-handler-prepare\"}[30s]) / irate(moja_cl_transfer_prepare_count{serviceName=\"central-handler-prepare\"}[120s])",
     "legendFormat": "Transfer Prepare - {{kubernetes_pod_name}}"
    },
    {
     "expr": "irate(moja_cl_transfer_position_sum{serviceName=\"central-handler-position\"}[30s]) / irate(moja_cl_transfer_position_count{serviceName=\"central-handler-position\"}[120s])",
     "legendFormat": "Transfer Position - {{kubernetes_pod_name}}"
    },
    {
     "expr": "irate(moja_cl_transfer_fulfil_sum{serviceName=\"central-handler-fulfil\"}[30s]) / irate(moja_cl_transfer_fulfil_count{serviceName=\"central-handler-fulfil\"}[120s])",
     "legendFormat": "Transfer Fulfil - {{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(irate(moja_cl_transfer_prepare_sum{serviceName=\"central-handler-prepare\"}[30s]) / irate(moja_cl_transfer_prepare_count{serviceName=\"central-handler-prepare\"}[120s]))",
     "legendFormat": "Transfer Prepare - Average"
    },
    {
     "expr": "avg(irate(moja_cl_transfer_position_sum{serviceName=\"central-handler-position\"}[30s]) / irate(moja_cl_transfer_position_count{serviceName=\"central-handler-position\"}[120s]))",
     "legendFormat": "Transfer Position - Average"
    },
    {
     "expr": "avg(irate(moja_cl_transfer_fulfil_sum{serviceName=\"central-handler-fulfil\"}[30s]) / irate(moja_cl_transfer_fulfil_count{serviceName=\"central-handler-fulfil\"}[120s]))",
     "legendFormat": "Transfer Fulfil - Average"
    }
   ]
  },
  {
   "title": "Number of Transfers Saved in DB",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 34 },
   "targets": [
    {
     "expr": "sum(sum_over_time( moja_cl_model_transfer_count{queryName=\"facade_saveTransferPrepared_transaction\", success=\"true\"}[$__interval]))",
     "legendFormat": "Transfer Prepares (success)"
    }
   ]
  },
  {
   "title": "CPU Usage by App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Central Services Total CPU Usage",
   "type": "gauge",
   "description": "Central Services Total CPU Usage",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*centralledger.*'}[2m]))"
    }
   ]
  },
  {
   "title": "Transfer Prepare Handler CPU Usage",
   "type": "gauge",
   "description": "Transfer Prepare Handler CPU Usage",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*centralledger-handler-transfer-prepare.*'}[2m]))"
    }
   ]
  },
  {
   "title": "Transfer Position Handler CPU Usage",
   "type": "gauge",
   "description": "Transfer Position Handler CPU Usage",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*centralledger-handler-transfer-position.*'}[2m]))"
    }
   ]
  },
  {
   "title": "Transfer Fulfil Handler CPU Usage",
   "type": "gauge",
   "description": "Transfer Fulfil Handler CPU Usage",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*centralledger-handler-transfer-fulfil.*'}[2m]))"
    }
   ]
  },
  {
   "title": "CPU Usage by Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Central-Service  - CPU Usage in Seconds by Pod",
   "type": "graph",
   "description": "Central-Service  - CPU Usage in Seconds by Pod",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(moja_cl_process_cpu_seconds_total{serviceName=~\"central.*\"}[2m]) * 100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Central-Service  - Event Loop Lag in Seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(moja_cl_nodejs_eventloop_lag_seconds{serviceName=~\"central.*\"}) by (serviceName)",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "Central-Service - # Pods for each Components",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*-centralledger-.*\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}