{
 "title": "Supporting Services - Callback Hander Service",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Party Callbacks / Sec",
   "type": "stat",
   "description": "Party Callbacks / Sec",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(tx_cb_perf_bucket{operation=\"get_parties_end2end\"}[30s]))",
     "legendFormat": "Party Callbacks / Sec"
    }
   ]
  },
  {
   "title": "Participant Callbacks / Sec",
   "type": "stat",
   "description": "Participant Callbacks / Sec",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(tx_cb_perf_bucket{operation=\"get_participants_end2end\"}[30s]))",
     "legendFormat": "Participant Callbacks / Sec"
    }
   ]
  },
  {
   "title": "Callback Service - Proccessed per sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tx_cb_perf_bucket[30s])) by (operation, success)",
     "legendFormat": "op:{{operation}} - success:{{success}}"
    }
   ]
  },
  {
   "title": "Callback Service - Processing Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(tx_cb_perf_sum[30s]) >=0 / rate(tx_cb_perf_count[30s]) >=0) by (operation, success)",
     "legendFormat": "Op {{operation}} - Success {{success}}"
    }
   ]
  }
 ]
}