version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  callback-handler-svc:
    container_name: callback-handler-svc
    image: mojaloop/callback-handler-svc:local
    build:
      context: .
      cache_from:
        - mojaloop/callback-handler-svc:local
    ports:
      - "3001:3001"
    networks:
      - mojaloop-net
    volumes:
      - ./config:/opt/app/dist/config
    environment:
      - LOG_LEVEL=debug
    healthcheck:
      test: wget -q http://localhost:3001/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
    user: root
