{
 "title": "Docker Prometheus Monitoring",
 "description": "Docker Monitoring Template",
 "tags": [
  "docker",
  "prometheus, ",
  "node-exporter",
  "cadvisor"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_exporter_build_info{name=~'$name'},instance)"
   },
   {
    "name": "env",
    "label": "Env",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "CPU Name",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Host Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(ALERTS)" }
   ]
  },
  {
   "title": "Targets Online",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 1, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg( node_filesystem_avail_bytes {mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Node Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVE"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "TRANSMIT"
    }
   ]
  },
  {
   "title": "Node Mermory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Available Memory"
    }
   ]
  },
  {
   "title": "Filesystem Available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes {job=\"node-exporter\", instance=~\".*9100\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"}) ",
     "legendFormat": "Free Storage"
    }
   ]
  },
  {
   "title": "CPU Usage by Core",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (cpu) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])*100)",
     "legendFormat": "CPU: {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Usage / Load",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[$__rate_interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[$__rate_interval]),1)) ))*100,100)",
     "legendFormat": "Max Core Utilization"
    },
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval]),1)) ))*100 or (avg_over_time(node_cpu_seconds_total{ mode!=\"total\", mode!=\"idle\"}[$__rate_interval]) or avg_over_time(node_cpu_seconds_total{ mode!=\"total\", mode!=\"idle\"}[$__rate_interval]))),100)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "I/O Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgpgin{}[$__rate_interval]) * 1024 or irate(node_vmstat_pgpgin{}[$__rate_interval]) * 1024",
     "legendFormat": "Page In"
    },
    {
     "expr": "rate(node_vmstat_pgpgout{}[$__rate_interval]) * 1024 or irate(node_vmstat_pgpgout{}[$__rate_interval]) * 1024",
     "legendFormat": "Page Out"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum((rate(node_disk_read_time_seconds_total{}[$__rate_interval]) / rate(node_disk_reads_completed_total{}[$__rate_interval])) or (irate(node_disk_read_time_seconds_total{}[$__rate_interval]) / irate(node_disk_reads_completed_total{}[$__rate_interval]))\nor avg_over_time(node_disk_reads_merged_total{}[$__rate_interval]) or avg_over_time(node_disk_reads_merged_total{}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum((rate(node_disk_write_time_seconds_total{}[$__rate_interval]) / rate(node_disk_writes_completed_total{}[$__rate_interval])) or (irate(node_disk_write_time_seconds_total{}[$__rate_interval]) / irate(node_disk_writes_completed_total{}[$__rate_interval])) or \navg_over_time(aws_rds_write_latency_average{}[$__rate_interval]) or avg_over_time(aws_rds_write_latency_average{}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{}[$__rate_interval]) * 4096 or irate(node_vmstat_pswpin{}[$__rate_interval]) * 4096",
     "legendFormat": "Swap In (Reads)"
    },
    {
     "expr": "rate(node_vmstat_pswpout{}[$__rate_interval]) * 4096 or irate(node_vmstat_pswpout{}[$__rate_interval]) * 4096",
     "legendFormat": "Swap Out (Writes)"
    }
   ]
  },
  {
   "title": "Memory Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(node_memory_MemTotal{}) without(job) - \n(max(node_memory_MemFree{}) without(job) + \nmax(node_memory_Buffers{}) without(job) + \n(max(node_memory_Cached_bytes{}) without (job) or \nmax(node_memory_Cached_bytes{}) without (job)))",
     "legendFormat": "Swap In (Reads)"
    },
    { "expr": "node_memory_MemFree_bytes{}", "legendFormat": "Free" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Buffers" },
    {
     "expr": "max(node_memory_Cached_bytes{}) without (job) or \nmax(node_memory_Cached_bytes{}) without (job)",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Container Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (id,name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 11, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 13, "w": 10, "x": 11, "y": 69 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Receive Rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_packets_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }} - receive (total)"
    },
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_errors_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }} - receive (error)"
    },
    {
     "expr": "sort_desc(sum (rate(container_network_receive_packets_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "All - receive (total)"
    },
    {
     "expr": "sort_desc(sum (rate(container_network_receive_errors_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "All - receive (error)"
    }
   ]
  },
  {
   "title": "Container Network Transmit Rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 11, "y": 82 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_packets_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }} - transmit (total)"
    },
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_errors_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }} - transmit (error)"
    },
    {
     "expr": "sort_desc(sum (rate(container_network_transmit_packets_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "All - transmit (total)"
    },
    {
     "expr": "sort_desc(sum (rate(container_network_transmit_errors_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "All - transmit (error)"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 21, "x": 0, "y": 20 },
     "targets": [
      { "expr": "ALERTS" }
     ]
    }
   ]
  },
  {
   "title": "Running Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running Versions",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 21, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "cadvisor_version_info",
       "legendFormat": "cAdvisor  Version: {{cadvisorVersion}}"
      },
      {
       "expr": "prometheus_build_info",
       "legendFormat": "Prometheus Version: {{version}}"
      },
      {
       "expr": "node_exporter_build_info",
       "legendFormat": "Node-Exporter Version: {{version}}"
      }
     ]
    }
   ]
  }
 ]
}