{
 "title": "Supporting Services - Callback Hander Service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Handler Ingress  - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(cbs_ing_callbackHandler_sum[$__rate_interval]) / rate(cbs_ing_callbackHandler_count[$__rate_interval]) >=0) by (operation, success, instance)",
     "legendFormat": "{{instance}} op: {{operation}} success: {{success}}"
    }
   ]
  },
  {
   "title": "Handler Ingress - Processed Per Second",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cbs_ing_callbackHandler_count[$__rate_interval])) by (operation, success, instance)",
     "legendFormat": "{{instance}}  op:{{operation}} success: {{success}}"
    },
    {
     "expr": "sum(rate(cbs_ing_callbackHandler_count[$__rate_interval])) by (operation, success)",
     "legendFormat": "Total op:{{operation}} success: {{success}}"
    }
   ]
  },
  {
   "title": "Handler Egress  - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(cbs_egress_callbackHandler_sum[$__rate_interval]) / rate(cbs_egress_callbackHandler_count[$__rate_interval]) >=0) by (operation, success, instance)",
     "legendFormat": "{{instance}}  op: {{operation}} success: {{success}}"
    }
   ]
  },
  {
   "title": "Handler Egress - Processed Per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cbs_egress_callbackHandler_count[$__rate_interval])) by (operation, success, instance)",
     "legendFormat": "{{instance}}  op:{{operation}} success: {{success}}"
    }
   ]
  },
  {
   "title": "E2E, Request, Response Calulations Proccessed Per Second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cbs_tx_cb_perf_count[$__rate_interval])) by (operation, success, instance)",
     "legendFormat": "{{instance}}  op:{{operation}} - success:{{success}}"
    }
   ]
  },
  {
   "title": "E2E, Request, Response Performance Timing Calculations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(cbs_tx_cb_perf_sum[$__rate_interval]) / rate(cbs_tx_cb_perf_count[$__rate_interval]) >= 0) by (operation, success, instance)",
     "legendFormat": "{{instance}}  op:{{operation}} - Success {{success}}"
    }
   ]
  }
 ]
}